apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-deploy
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-deploy
  type: LoadBalancer
